version: '3.9'

services:
  server:
    image: server:latest
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      - EUREKA_SERVER_HOSTNAME=server
    networks:
      - microsservicos

  veiculo-service:
    image: veiculo-service:latest
    container_name: veiculo-service
    build:
      context: ./veiculo-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_URL=http://server:8761/eureka
    depends_on:
      - server
    networks:
      - microsservicos
networks:
  microsservicos:
