apiVersion: apps/v1
kind: Deployment
metadata:
  name: veiculo-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: veiculo-service
  template:
    metadata:
      labels:
        app: veiculo-service
    spec:
      containers:
      - name: veiculo-service
        image: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: veiculo-service
spec:
  type: LoadBalancer
  selector:
    app: veiculo-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080