apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: at-server
spec:
  selector:
    matchLabels:
      app: at-server
  replicas: 1
  template:
    metadata:
      labels:
        app: at-server
    spec:
      containers:
        - name: at-server
          image: server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  ports:
    - port: 8761
      targetPort: 8761
      nodePort: 31000
  type: NodePort
  selector:
    app: at-server