apiVersion: apps/v1
kind: Deployment
metadata:
  name: veiculo-service-deployment
  labels:
    app: veiculo-service
spec:
  selector:
    matchLabels:
      app: veiculo-service
  replicas: 3
  template:
    metadata:
      labels:
        app: veiculo-service
    spec:
      containers:
        - name: veiculo-service
          image: veiculo-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: veiculo-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31001
  selector:
    app: veiculo-service