version: '3.9'

services:
  tp2-server:
    container_name: tp2-server
    image: tp2-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - tp2-net

  mysql-db:
    container_name: mysql-db
    image: mysql:8.0
    environment:
      - MYSQL_USER=superuser
      - MYSQL_PASSWORD=12345678
      - MYSQL_ROOT_PASSWORD=abcde
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - tp2-net

  tp2-client:
    container_name: tp2-client
    image: tp2-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      # - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/tp2-database?createDatabaseIfNotExist=Yes
      # - SPRING_DATASOURCE_USERNAME=root
      # - SPRING_DATASOURCE_PASSWORD=abcde
      - MYSQL_HOST=jdbc:mysql://mysql-db:3306
      - SERVER_URL=http://tp2-server:8761/eureka
    depends_on:
      - tp2-server
      - mysql-db
    networks:
      - tp2-net

networks:
  tp2-net:

volumes:
  mysql-data: